[book]
authors = ["hyperswine"]
language = "en"
multilingual = false
src = "src"
title = "Jasen's Projects"

[output.html]
mathjax-support = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.inline-mathjax]
